README.md, contracts/merkleTree.scrypt, contracts/testMerkleTree.scrypt, tests/js/testMerkleTree.scrypttest.js
This PR implements the merkletree contract and unit tests.
=> Add merkleTree contract

contracts/SuperAsset10.scrypt, contracts/util.scrypt, deployments/superAsset10.js
**Changes:**
- Add `Utils.writeVarMinimalPushdata` to write minimally encoded bytes
- Add SuperAsset10.scrypt smart contract and superAsset10.js deployment example.
**Learn more:**
- Announcement: https://blog.matterpool.io/launch-of-superasset-sa10-nft-smart-contract-for-bitcoin/
- SuperAsset white paper: https://bitcoinfiles.org/t/d6c18189966ea060452bcf59157235f2e15df3abf7383d9d450acff69cf29181
- Github: https://github.com/MatterPool/superasset-js
**Example transactions:**
Deploy: https://whatsonchain.com/tx/afd702c8ccd5b3193f7be0afaace551430593b2e1af7264908e003f63bd5883f
Transfer (mint with JSON paylod update): https://whatsonchain.com/tx/9a731acb3ef5af7ec97a14725f481aa9cac69beba7567c596e155cd1993f2905
Transfer (Update with hex payload): …
=> Add SimpleAsset10

contracts/binaryOption.scrypt, deployments/binaryoption.js
build the binaryoption contract with oracle data
=> binaryoption contract

contracts/nonFungibleToken.scrypt, deployments/nonFungibleToken.js, tests/js/nonFungibleToken.scrypttest.js
Fix: When receiver pretending to be the issuer, repeated minting happens.
=> bug fix: nonFungibleToken repeated minting

contracts/merkleTree2.scrypt, contracts/tokenSwap.scrypt, deployments/binaryoption.js, deployments/tokenSwap.js
tokenswap contract implemens a token contract with swap pool
=> add tokenSwap contract

.vscode/launch.json, contracts/rpuzzle.scrypt, deployments/rpuzzle.js, tests/js/rpuzzle.scrypttest.js
Added new RPuzzle contract, test and deployment scripts.
=> Added RPuzzle contract

.vscode/launch.json, contracts/simpleBVM.scrypt, deployments/simpleBVM.js, tests/js/simpleBVM.scrypttest.js
A very simple script interpreter. It parses an input script and executes it.
The interpreter supports OP_ADD and OP_SUB, and the numbers 1 - 16.
The script sig string is restricted to 18 bytes.
=> Added SimpleBVM contract

.vscode/launch.json, contracts/xorPuzzle.scrypt, deployments/xorPuzzle.js, tests/js/xorPuzzle.scrypttest.js
Using:
xorResult = data ^ sha256(pubKey + data)
instead of:
xorResult = data ^ pubKey
=> Security enhancements. 

contracts/recurring.scrypt, deployments/recurring.js
A modified version of faucet.scrypt and faucet.js to have a recurring payment smart contract !
=> Recurring payment smart contract

contracts/dynamicArray.scrypt, contracts/dynamicArrayDemo.scrypt, tests/js/dynamicArrayDemo.scrypttest.js
=> Dynamicarray

contracts/enforceAgentBitcoinTransfer.scrypt, contracts/testUtil.scrypt, contracts/util.scrypt, helper.js, tests/js/enforce_agent_bitcoin_transfer.scrypttest.js, tests/testFixture/utiltest.scrypt
Also update Util.sigHashType function to remove "fork identifier bytes" as discussed.
=> Add enforceAgentBitcoinTransfer contract

contracts/base58.scrypt
=> compile will fail

contracts/faucetV2.scrypt, testnet/faucetV2.js, tests/js/faucetV2.scrypttest.js
- deposit money into the contract, without cold down, implemented with sighash single and anyonecanpay flag
- withdraw money from the contract, must meet the cold down intervals
- destroy contract, only the creator can recycle the money locked in this contract
=> Add a new faucet contract

contracts/shift10.scrypt, contracts/shift10Test.scrypt, contracts/shiftTest.scrypt, tests/js/shift.scrypttest.js, tests/js/shift10.scrypttest.js
- Shift10 with tests
- using bytes instead of int to pass a string
=> Base 10 shifts (mpapec)

contracts/conwaygol.scrypt, tests/js/conwaygol.scrypttest.js
Changes to be committed:
modified:   contracts/conwaygol.scrypt
modified:   tests/js/conwaygol.scrypttest.js
=> Rewrite Game of Life example using array

contracts/schnorr.scrypt, tests/js/schnorr.scrypttest.js
modified:   contracts/schnorr.scrypt
new file:   tests/js/schnorr.scrypttest.js
=> rewrite schnorr using EC library #173

tests/js/ringsig.scrypttest.js
Currently compiling ringsig.scrypt with compileContract() will give an error,
It needs to be compiled in the dev branch with compileContractAsync(),
Testing is done on the dev branch.
=> test ring signature #172

contracts/bn256.scrypt, tests/py/test_zksnark.py
To accept ZoKrates VK & proof as they are, without switching coordinates.
=> Switch coords in G2 x and y.

.asm/apply_asm.js, .asm/asm.json, package-lock.json, package.json, src/contracts/asmDemo.ts, tests/local/asm.test.ts, tests/local/catastropheBond.test.ts
⚠️ Merge after https://github.com/sCrypt-Inc/scrypt-ts/pull/400 ends up in a release. ⚠️
=> Added inline ASM example.

tests/local/numbergs.test.ts, tests/testnet/numbergs.ts
As per #256 ( Update and rename numbergs.ts to numberGuess.ts ) changes were made in `src/contracts/numbergs.ts` i.e.
1. `numbergs.ts` file name changed to `numberGuess.ts`
2. Class name `Numbergs` changed to `NumberGuess`
These files were imported in 2 files 
1. `tests/local/numbergs.ts`
2. `tests/testnet/numbergs.ts`
Therefore importing line of code & the class names were changed in the above files. 
solves #259
=> Modified numbergs.ts in tests/local and tests/testnet as per #256

package-lock.json, package.json, src/contracts/cointoss.ts, src/contracts/multiPartyHashPuzzle.ts, src/contracts/ordinalAuction.ts, src/contracts/perceptron2.ts, tests/local/ordinalAuction.test.ts, tests/testnet/ordinalAuction.ts, tests/testnet/p2pkh-anyonecanpay.ts
⚠️ Merge after https://github.com/sCrypt-Inc/scrypt-ts/pull/433 is merged and released.
=> Ordinal auction contract
